a=1212372362534
b=True
c="rifat"
d=None
e=complex(8,2)
list1=[8,25,2.5,[-4,5],["apple","banana","cherry"]]
tuple1=("Rifat","Sumon","redwan",("Hi","hello"))
dict1={"Name":"Rifat",
        "Age":"23",
        "Class":"15"}
print(a)
print(b)
print(c)
print(d)
print(e)
print(list1)
print(tuple1)
print(dict1)
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))

x=123
y=9
print(x+y)
